# coding: utf-8

"""
    WSO2 API Manager - Token

    This document specifies a **RESTful API** for WSO2 **API Manager** - Token .  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_tokenclient
from wso2_apim_tokenclient.rest import ApiException
from wso2_apim_tokenclient.models.access_token import AccessToken


class TestAccessToken(unittest.TestCase):
    """ AccessToken unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessToken(self):
        """
        Test AccessToken
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = wso2_apim_tokenclient.models.access_token.AccessToken()
        pass


if __name__ == '__main__':
    unittest.main()
