# coding: utf-8

"""
    WSO2 API Manager - Token

    This document specifies a **RESTful API** for WSO2 **API Manager** - Token .  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_tokenclient
from wso2_apim_tokenclient.rest import ApiException
from wso2_apim_tokenclient.apis.token_api import TokenApi


class TestTokenApi(unittest.TestCase):
    """ TokenApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_tokenclient.apis.token_api.TokenApi()

    def tearDown(self):
        pass

    def test_token_post(self):
        """
        Test case for token_post

        generate access tokens and authorize them
        """
        pass


if __name__ == '__main__':
    unittest.main()
