# coding: utf-8

"""
    WSO2 API Manager - Token

    This document specifies a **RESTful API** for WSO2 **API Manager** - Token .  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .access_token import AccessToken
from .o_auth2_error import OAuth2Error
from .o_auth2_error_object import OAuth2ErrorObject
