# coding: utf-8

"""
    WSO2 API Manager - Token

    This document specifies a **RESTful API** for WSO2 **API Manager** - Token .  It is written with [swagger 2](http://swagger.io/). 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OAuth2Error(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'error_description': 'str'
    }

    attribute_map = {
        'error': 'error',
        'error_description': 'error_description'
    }

    def __init__(self, error=None, error_description=None):
        """
        OAuth2Error - a model defined in Swagger
        """

        self._error = None
        self._error_description = None

        self.error = error
        self.error_description = error_description

    @property
    def error(self):
        """
        Gets the error of this OAuth2Error.
        Error message.

        :return: The error of this OAuth2Error.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """
        Sets the error of this OAuth2Error.
        Error message.

        :param error: The error of this OAuth2Error.
        :type: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")

        self._error = error

    @property
    def error_description(self):
        """
        Gets the error_description of this OAuth2Error.
        A detail description about the error message. 

        :return: The error_description of this OAuth2Error.
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """
        Sets the error_description of this OAuth2Error.
        A detail description about the error message. 

        :param error_description: The error_description of this OAuth2Error.
        :type: str
        """
        if error_description is None:
            raise ValueError("Invalid value for `error_description`, must not be `None`")

        self._error_description = error_description

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OAuth2Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
